### ISSUE TITLE
`request-filename` with encoded `%20`

### ISSUE THREAD

**Issue by jayenashar** [paultuckey/urlrewritefilter#226] opened 2017-12-26 06:28 UTC
Hi Paul, I have some files with spaces in their names.  Also I have some rules with:

```
        <condition type="request-filename" operator="notfile" next="and" />
        <condition type="request-filename" operator="notdir" />
```

These files are matching these conditions/rules as [I guess] the `request-filename` has `%20` but the file has ` `, so urlrewritefilter matched `notfile` and `notdir`.

If there's a way to `unescape` the `request-filename` I couldn't figure it out.  I did try `<urlrewrite  decode-using="null">` with no luck.

This is not a big issue for me as I am now renaming the files, so I am just recording it in case someone else stumbles onto it.

**Comment by paultuckey** [comment] 2018-01-15 02:39
The code for `request-filename` uses `request.getRequestURI()` then `getServletContext().getRealPath()`.  Normally `getRealPath` should handle escaped paths.

What app server are you using the filter on?

**Comment by jayenashar** [comment] 2018-01-15 02:55
tomcat7 on 32-bit openjdk8 on both 32-bit debian and 64-bit debian.  is that what you want to know?

**Comment by bdw429s** [comment] 2022-05-03 03:59
> Normally getRealPath should handle escaped paths.

@paultuckey I've never heard of this, nor does it make any sense.  The docs for [`ServletContext.getRealPath()`](https://docs.oracle.com/javaee/6/api/javax/servlet/ServletContext.html#getRealPath(java.lang.String)) say it accepts a path, not a URI.  There's nothing in the spec about URL decoding, and I have the same issue with Undertow which also expects a path with no URL encoding present.

This ticket is also basically a duplicate of this ticket: https://github.com/paultuckey/urlrewritefilter/issues/218

**Comment by bdw429s** [comment] 2022-05-03 04:18
The fix appears to just be to convert the URI into a path which will decode any URI escape sequences.  Create a new instance of `java.net.URI` and then call `URI.getPath()` which will finally give you a decoded string suitable for `getRealPath()`.

**Comment by bdw429s** [comment] 2022-12-12 23:19
@paultuckey Would you accept a pull request for this?  It seems like such a simple fix.

**Comment by paultuckey** [comment] 2022-12-13 04:07
Yes, happy to take a PR.  In the past all changes were tested on on as many containers as possible.  The setup I had for this (https://github.com/paultuckey/urlrewritefilter/tree/master/container-test) doesn't work anymore and needs to be upgraded.

**Comment by bdw429s** [comment] 2023-04-04 16:02
@paultuckey Apologies, I totally missed your last reply.  Please see this pull request with a new passing test case

https://github.com/paultuckey/urlrewritefilter/pull/250

cc/ @jclausen

**Comment by paultuckey** [comment] 2023-07-17 22:51
#250 is now merged, assuming this is now fixed.

**Closed by paultuckey** 2023-07-17 22:51 UTC
